export const tabs = {
  invoice: 'Invoice',
  history: 'History',
  notes: 'Notes',
};

export const ui = {
  notDue: 'Not due',
  daysUntilDue: 'days until due',
  totalAmount: 'Total Amount',
  openAmount: 'Open Amount',
  vatAmount: 'VAT. Amount',
  dueDate: 'Due Date',
  paidOnLabel: 'Paid On',
  customerAvDelay: 'Customer av delay',
  payments: 'Payments',
  add: 'Add',
  paidOn: 'Paid on',
  noPayments: 'No payments yet.',
  addPayment: 'Add Payment',
  amount: 'Amount',
  cancel: 'Cancel',
  productsServices: 'Products / Services',
  noItems: 'No items.',
  subtotal: 'Subtotal:',
  discount: 'Discount:',
  vat: 'VAT:',
  total: 'Total:',
  paymentMethod: 'Payment method: Bank transfer',
  issuedBy: 'Issued by:',
  signature: 'Signature: ____________________',
  changeStyle: 'Change Style',
  historyContent: 'History content here...',
  notesContent: 'Notes content here...',
  voidInvoice: 'Void Invoice',
  changeStatus: 'Change Status',
  editInvoice: 'Edit Invoice',
};
