<?php

return [
    'AED' => 'Dirham EAU',
    'AUD' => 'Dolar Australian',
    'BRL' => 'Real Brazilian',
    'CAD' => 'Dolar Canadian',
    'CHF' => 'Franc Elvețian',
    'CNY' => 'Yuan Chinezesc',
    'CZK' => 'Coroană Cehă',
    'DKK' => 'Coroană Daneză',
    'EGP' => 'Liră Egipteană',
    'EUR' => 'Euro',
    'GBP' => 'Liră Sterlină',
    'HUF' => 'Forint Maghiar',
    'INR' => 'Rupie Indiană',
    'JPY' => 'Yen Japonez',
    'KRW' => 'Won Sud-Coreean',
    'MDL' => 'Leu Moldovenesc',
    'MXN' => 'Peso Mexican',
    'NOK' => 'Coroană Norvegiană',
    'NZD' => 'Dolar Neo-Zeelandez',
    'PLN' => 'Zlot Polonez',
    'RON' => 'Leu Românesc',
    'RSD' => 'Dinar Sârbesc',
    'RUB' => 'Rublă Rusească',
    'SEK' => 'Coroană Suedeză',
    'THB' => 'Baht Tailandez',
    'TRY' => 'Liră Turcească',
    'UAH' => 'Hrivnă Ucraineană',
    'USD' => 'Dolar American',
    'ZAR' => 'Rand Sud-African',
];
